specVersion: 0.0.6
description: fi.woo.org
repository: https://github.com/woonetwork/woofi_subgraph
schema:
  file: ./woofi.graphql
dataSources:
  - kind: ethereum/contract
    name: WOOFiCrossRouterV5_1
    network: base
    source:
      address: "0xB84aEfEF2DDDE628d5c7F1fba320dE63e3f4757c"
      abi: WOOFiCrossRouterV5
      startBlock: 25288772
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WOOFiCrossSwapOnSrcChain
        - WOOFiCrossSwapOnDstChain
      abis:
        - name: WOOFiCrossRouterV5
          file: ../abis/WOOFiCrossRouterV5_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WOOFiCrossSwapOnSrcChain(uint32,indexed bytes32,indexed address,indexed address,address,uint256,address,uint256,uint256,uint8,uint256)
          handler: handleWOOFiCrossRouterV5WOOFiCrossSwapOnSrcChain_1
          receipt: true
        - event: WOOFiCrossSwapOnDstChain(uint32,indexed bytes32,indexed address,indexed address,address,uint256,uint256,address,address,uint256,uint256,uint8,uint256)
          handler: handleWOOFiCrossRouterV5WOOFiCrossSwapOnDstChain_1
          receipt: true
      file: ../src/mappings/wooCrossChainRouter/index.ts
  - kind: ethereum/contract
    name: StargateBridgeV1_1
    network: base
    source:
      address: "0xAF54BE5B6eEc24d6BFACf1cce4eaF680A8239398"
      abi: StargateBridgeV1
      startBlock: 2359377
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - SendMsg
      abis:
        - name: StargateBridgeV1
          file: ../abis/StargateBridgeV1_1.json
      eventHandlers:
        - event: SendMsg(uint8,uint64)
          handler: handleStargateBridgeV1SendMsg_1
          receipt: true
      file: ../src/mappings/stargateBridge/index.ts
  - kind: ethereum/contract
    name: WooCrossChainRouterV4_1
    network: base
    source:
      address: "0xCa10E8825FA9F1dB0651Cd48A9097997DBf7615d"
      abi: WooCrossChainRouterV4
      startBlock: 5513026
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooCrossSwapOnSrcChain
        - WooCrossSwapOnDstChain
      abis:
        - name: WooCrossChainRouterV4
          file: ../abis/WooCrossChainRouterV4_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooCrossSwapOnSrcChain(indexed uint256,indexed address,indexed address,address,uint256,address,uint256,uint256,uint8,uint256)
          handler: handleWooCCRouterV4WooCrossSwapOnSrcChain_1
          receipt: true
        - event: WooCrossSwapOnDstChain(indexed uint256,indexed address,indexed address,address,uint256,address,address,uint256,uint256,uint8,uint256)
          handler: handleWooCCRouterV4WooCrossSwapOnDstChain_1
          receipt: true
      file: ../src/mappings/wooCrossChainRouter/index.ts
  - kind: ethereum/contract
    name: WooCrossChainRouterV3_1
    network: base
    source:
      address: "0xe47Fec1c72850d867a1655C4C5902de7728CA205"
      abi: WooCrossChainRouterV3
      startBlock: 4291217
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooCrossSwapOnSrcChain
        - WooCrossSwapOnDstChain
      abis:
        - name: WooCrossChainRouterV3
          file: ../abis/WooCrossChainRouterV3_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooCrossSwapOnSrcChain(indexed uint256,indexed address,indexed address,address,uint256,address,uint256,uint256,uint8,uint256)
          handler: handleWooCCRouterV3WooCrossSwapOnSrcChain_1
          receipt: true
        - event: WooCrossSwapOnDstChain(indexed uint256,indexed address,indexed address,address,uint256,address,address,uint256,uint256,uint8,uint256)
          handler: handleWooCCRouterV3WooCrossSwapOnDstChain_1
          receipt: true
      file: ../src/mappings/wooCrossChainRouter/index.ts
  - kind: ethereum/contract
    name: WooCrossChainRouterV2_1
    network: base
    source:
      address: "0xF314FA27066bdde92e6122059B103E8899D0a096"
      abi: WooCrossChainRouterV2
      startBlock: 2359377
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooCrossSwapOnSrcChain
        - WooCrossSwapOnDstChain
      abis:
        - name: WooCrossChainRouterV2
          file: ../abis/WooCrossChainRouterV2_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooCrossSwapOnSrcChain(indexed uint256,indexed address,indexed address,address,uint256,uint256,uint256)
          handler: handleWooCCRouterV2WooCrossSwapOnSrcChain_1
          receipt: true
        - event: WooCrossSwapOnDstChain(indexed uint256,indexed address,indexed address,address,uint256,address,address,uint256,uint256)
          handler: handleWooCCRouterV2WooCrossSwapOnDstChain_1
          receipt: true
      file: ../src/mappings/wooCrossChainRouter/index.ts
  - kind: ethereum/contract
    name: WooRouterV2_2
    network: base
    source:
      address: "0x4c4AF8DBc524681930a27b2F1Af5bcC8062E6fB7"
      abi: WooRouterV2
      startBlock: 11080369
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooRouterSwap
      abis:
        - name: WooRouterV2
          file: ../abis/WooRouterV2_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooRouterSwap(uint8,indexed address,indexed address,uint256,uint256,address,indexed address,address)
          handler: handleWooRouterV2WooRouterSwap_2
          receipt: true
      file: ../src/mappings/wooRouter/index.ts
  - kind: ethereum/contract
    name: WooRouterV2_1
    network: base
    source:
      address: "0x27425e9FB6A9A625E8484CFD9620851D1Fa322E5"
      abi: WooRouterV2
      startBlock: 2178413
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooRouterSwap
      abis:
        - name: WooRouterV2
          file: ../abis/WooRouterV2_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooRouterSwap(uint8,indexed address,indexed address,uint256,uint256,address,indexed address,address)
          handler: handleWooRouterV2WooRouterSwap_1
          receipt: true
      file: ../src/mappings/wooRouter/index.ts
  - kind: ethereum/contract
    name: WooPPV2_2
    network: base
    source:
      address: "0xEd9e3f98bBed560e66B89AaC922E29D4596A9642"
      abi: WooPPV2
      startBlock: 13588072
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooSwap
      abis:
        - name: WooPPV2
          file: ../abis/WooPPV2_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooSwap(indexed address,indexed address,uint256,uint256,address,indexed address,address,uint256,uint256)
          handler: handleWooPPV2WooSwap_2
          receipt: true
      file: ../src/mappings/wooPP/index.ts
  - kind: ethereum/contract
    name: WooPPV2_4
    network: base
    source:
      address: "0x5520385bFcf07Ec87C4c53A7d8d65595Dff69FA4"
      abi: WooPPV2
      startBlock: 27656046
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooSwap
      abis:
        - name: WooPPV2
          file: ../abis/WooPPV2_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooSwap(indexed address,indexed address,uint256,uint256,address,indexed address,address,uint256,uint256)
          handler: handleWooPPV2WooSwap_4
          receipt: true
      file: ../src/mappings/wooPP/index.ts
  - kind: ethereum/contract
    name: WooPPV2_1
    network: base
    source:
      address: "0xb130a49065178465931d4f887056328CeA5D723f"
      abi: WooPPV2
      startBlock: 2174191
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - WooSwap
      abis:
        - name: WooPPV2
          file: ../abis/WooPPV2_1.json
        - name: ERC20
          file: ../abis/ERC20.json
      eventHandlers:
        - event: WooSwap(indexed address,indexed address,uint256,uint256,address,indexed address,address,uint256,uint256)
          handler: handleWooPPV2WooSwap_1
          receipt: true
      file: ../src/mappings/wooPP/index.ts
  - kind: ethereum
    name: WooTokenOFT
    network: base
    source:
      address: "0xf3df0a31ec5ea438150987805e841f960b9471b6"
      abi: WooTokenOFT
      startBlock: 23242749
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - OFTReceived
        - OFTSent
      abis:
        - name: WooTokenOFT
          file: ../abis/WooTokenOFT.json
      eventHandlers:
        - event: OFTReceived(indexed bytes32,uint32,indexed address,uint256)
          handler: handleOFTReceived
        - event: OFTSent(indexed bytes32,uint32,indexed address,uint256,uint256)
          handler: handleOFTSent
      file: ../src/mappings/wooTokenOFT/index.ts
